# Generated by Django 3.2 on 2021-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklet',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='booklet',
            name='title',
            field=models.CharField(blank='True', max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
